apiVersion: v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      name: openldap
      labels:
        app: openldap
   spec:
     containers:
     - name: openldap
       image: openldap
       ports:
       - containerPort: 389
       - containerort: 636
