apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  selector:
    app: openldap
  type: ClusterIP
  ports:
  - port: 389
    targetPort: 389
  - port: 636
    targetPort: 636
