apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  labels:
    app: phpldapadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      name: phpldapadmin
      labels:
        app: phpldapadmin
    spec:
      containers:
      - name: phpldapadmin
        image: sensorgraph/phpldapadmin:latest
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: openldap
        ports:
        - containerPort: 80
        - containerPort: 443
