apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  labels:
    app: phpldapadmin
spec:
  selector:
    app: phpldapadmin
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
