- name: Create base entry for groups and users
  ldap_entry:
    dn: "{{ item }}"
    objectClass: organizationalUnit
    start_tls : true
    validate_certs: no
    state: present
    server_uri: "{{ net.kibadex.ldap.uri }}"
    bind_dn:  "{{ net.kibadex.ldap.bind_dn }}"
    bind_pw: "{{ net.kibadex.ldap.bind_pw }}"
  with_items: 
    - ou=groups,{{ net.kibadex.ldap.base_dn }}
    - ou=users,{{ net.kibadex.ldap.base_dn }}
    - ou=bots,ou=users,{{ net.kibadex.ldap.base_dn }}