- name: Create an entry on the LDAP for a user
  ldap_entry:
    dn: "cn={{ item.firstnames }} {{ item.lastnames|upper }},ou=users,{{ net.kibadex.ldap.base_dn }}"
    objectClass:
      - inetOrgPerson
      - posixAccount
      - ldapPublicKey
    attributes:
      uid: "{{ item.login }}"
      uidNumber: "{{ item.uid }}"
      gidNumber: "{{ item.gid }}"
      userPassword: "{{ item.password }}"
      mail: "{{ item.mail }}"
      givenName: "{{ item.firstnames }}"
      sn: "{{ item.lastnames|upper }}"
      homeDirectory: "{{ item.home_directory }}"
      sshPublicKey: "{{ item.ssh_public_key }}"
    state: "{{ item.state }}"
    server_uri: "{{ net.kibadex.ldap.server.uri }}"
    start_tls : "{{ net.kibadex.ldap.server.start_tls }}"
    validate_certs: "{{ net.kibadex.ldap.server.validate_certs }}"
    bind_dn:  "{{ net.kibadex.ldap.bind_dn }}"
    bind_pw: "{{ net.kibadex.ldap.bind_pw }}"
  with_items: "{{ ldap_users }}"