FROM osixia/phpldapadmin:0.9.0

ENV PHPLDAPADMIN_LDAP_HOSTS="ldap.kibadex.net"
ENV PHPLDAPADMIN_SERVER_ADMIN="mohamed.basri@outlook.com"

# Transport Layer Security
ENV PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME="kibadex.net.crt"
ENV PHPLDAPADMIN_HTTPS_CRT_FILENAME="phpldapadmin.kibadex.net.crt"
ENV PHPLDAPADMIN_HTTPS_KEY_FILENAME="phpldapadmin.kibadex.net.key"