apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  serviceName: openldap
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      name: openldap
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: sensorgraph/openldap
        ports:
        - containerPort: 389
        - containerPort: 636
        volumeMounts:
        - name: openldap
          mountPath: /var/lib/ldap
          subPath: var/lib/ldap
        - name: openldap
          mountPath: /etc/ldap/slapd.d
          subPath: etc/ldap/slapd.d
        env:
        - name: LDAP_ORGANISATION
          valueFrom:
            configMapKeyRef:
              name: openldap
              key: ldap_organisation

        - name: LDAP_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: openldap
              key: ldap_domain

        - name: LDAP_READONLY_USER
          valueFrom:
            configMapKeyRef:
              name: openldap
              key: ldap_readonly_user

        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openldap
              key: ldap_admin_password

        - name: LDAP_READONLY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openldap
              key: ldap_readonly_password
  volumeClaimTemplates:
  - metadata:
      name: openldap
      labels:
        app: openldap
    spec:
      storageClassName: aws-ebs-gp2
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi