apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  storageClassName: aws-ebs-gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
