# http://localhost:8001/api/v1/namespaces/default/services/https:phpldapadmin:443/proxy/
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  selector:
    app: openldap
  type: ClusterIP
  ports:
  - name: notsecure
    port: 389
    targetPort: 389
  - name: secure
    port: 636
    targetPort: 636
