- name: Run OpenLDAP for create the entries
  connection:  local
  hosts: localhost
  pre_tasks:
    - include_vars: group_vars/net/kibadex/main.yml
    - include_vars: group_vars/net/kibadex/groups/main.yml
    - include_vars: group_vars/net/kibadex/users/main.yml
    - include_tasks: tasks/init.yml
  tasks:
    - include_tasks: tasks/groups.yml
    - include_tasks: tasks/users.yml