ldap_groups:
  - dn: cn=managements
    gid: 500
    state: present
  - dn: cn=labs
    gid: 501
    state: present

  # Software groups
  ## Grafana
  - dn: cn=superadmins,ou=grafana,ou=softwares
    gid: 900
    state: present
  - dn: cn=admins,ou=grafana,ou=softwares
    gid: 901
    state: present
  - dn: cn=editors,ou=grafana,ou=softwares
    gid: 902
    state: present
  - dn: cn=viewers,ou=grafana,ou=softwares
    gid: 903
    state: present
  ## Rabbitmq
  - dn: cn=rabbitmq,ou=softwares
    gid: 910
    state: present
  ## Uchiwa
  - dn: cn=uchiwa,ou=softwares
    gid: 920
    state: present
  ## Chronograph
  - dn: cn=chronograph,ou=softwares
    gid: 930
    state: present